[program:newpr-backend-queue]
process_name=%(program_name)s_%(process_num)02d
directory=%(here)s/../
command=/bin/bash -c "brew link php@8.5 --force && /opt/homebrew/bin/php artisan queue:work --sleep=3 --tries=3"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=zn
numprocs=1
redirect_stderr=true
stdout_logfile=%(here)s/../storage/logs/queue.log
environment=PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
