[program:newpr-backend-octane]
process_name=%(program_name)s_%(process_num)02d
directory=%(here)s/../
command=/usr/local/bin/php artisan octane:start --port=8011
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
startsecs=5
startretries=3
user=www-data
numprocs=1
redirect_stderr=false
stdout_logfile=%(here)s/../storage/logs/octane.log
stderr_logfile=%(here)s/../storage/logs/octane-error.log
